const express = require('express');
const mongoose = require('mongoose');
const { authenticate, isAdmin } = require('../utils/auth');

const AiEmail = require('../models/AiEmail');

const {
  processIncomingEmail,
  getPendingAiEmails,
  getAllAiEmails,
  getAiEmailById,
  manualSendAiEmail,
  getAiSettings,
  updateAiSettings,
  generateAiDraft,
  normalizeIdList,
} = require('../services/aiEmailService');

const router = express.Router();

// ── Settings ──
router.get('/settings', authenticate, isAdmin, async (req, res) => {
  try {
    const settings = await getAiSettings();
    res.json({ success: true, settings });
  } catch (error) {
    console.error('Error loading AI settings:', error);
    res
      .status(500)
      .json({ success: false, message: 'Failed to load AI settings.' });
  }
});

router.patch('/settings', authenticate, isAdmin, async (req, res) => {
  try {
    const updatedBy = req.user && req.user.id ? req.user.id : null;
    const settings = await updateAiSettings(req.body, updatedBy);
    res.json({ success: true, settings });
  } catch (error) {
    console.error('Error updating AI settings:', error);
    res
      .status(500)
      .json({ success: false, message: 'Failed to update AI settings.' });
  }
});

// ── List / fetch ──
router.get('/', authenticate, isAdmin, async (req, res) => {
  try {
    const { status, limit, page } = req.query;
    const pageNum = Math.max(1, Number(page) || 1);
    const limitNum = Math.min(100, Math.max(1, Number(limit) || 25));

    const result = status
      ? await getAllAiEmails({ status, page: pageNum, limit: limitNum })
      : await getPendingAiEmails({ page: pageNum, limit: limitNum });

    res.json({
      success: true,
      emails: result.emails,
      pagination: {
        total: result.total,
        page: result.page,
        limit: result.limit,
        totalPages: Math.max(1, Math.ceil(result.total / result.limit)),
      },
    });
  } catch (error) {
    console.error('Error loading AI emails:', error);
    res
      .status(500)
      .json({ success: false, message: 'Failed to load AI emails.' });
  }
});

router.get('/:id', authenticate, isAdmin, async (req, res) => {
  try {
    const email = await getAiEmailById(req.params.id);
    if (!email) {
      return res
        .status(404)
        .json({ success: false, message: 'AI email not found.' });
    }
    res.json({ success: true, email });
  } catch (error) {
    console.error('Error loading AI email:', error);
    res
      .status(500)
      .json({ success: false, message: 'Failed to load AI email.' });
  }
});

// ── Regenerate AI draft ──
router.post('/:id/regenerate', authenticate, isAdmin, async (req, res) => {
  try {
    const aiEmail = await AiEmail.findById(req.params.id);
    if (!aiEmail) {
      return res
        .status(404)
        .json({ success: false, message: 'AI email not found.' });
    }
    if (aiEmail.status === 'sent') {
      return res
        .status(400)
        .json({ success: false, message: 'Email has already been sent.' });
    }

    const result = await generateAiDraft({
      from: aiEmail.replyToEmail || aiEmail.from,
      subject: aiEmail.subject || '',
      body: aiEmail.body,
    });

    aiEmail.category = result.category;
    aiEmail.confidence = result.confidence;
    aiEmail.aiDraft = result.draft;
    aiEmail.aiReason = result.reason;
    aiEmail.dataUsed = result.dataUsed;
    aiEmail.replyToEmail = result.effectiveEmail || aiEmail.from;

    if (result.parent) {
      const pid = result.parent.id || result.parent._id || null;
      if (pid && mongoose.Types.ObjectId.isValid(pid)) {
        aiEmail.parentId = pid;
      }
    }
    if (result.context && result.context.players) {
      aiEmail.playerIds = normalizeIdList(
        result.context.players.map((p) => p.id),
      );
    }
    if (result.context && result.context.registrations) {
      aiEmail.registrationIds = normalizeIdList(
        result.context.registrations.map((r) => r.playerId),
      );
    }
    if (result.context && result.context.payments) {
      aiEmail.paymentIds = normalizeIdList(
        result.context.payments.map((p) => p.paymentId),
      );
    }

    aiEmail.status = 'draft_ready';
    aiEmail.requiresHumanReview = true;
    aiEmail.reviewReason = 'Regenerated by administrator.';

    await aiEmail.save();
    res.json({ success: true, email: aiEmail });
  } catch (error) {
    console.error('Regenerate error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
});

// ── Manual send ──
router.post('/:id/send', authenticate, isAdmin, async (req, res) => {
  try {
    const aiEmail = await AiEmail.findById(req.params.id);
    if (!aiEmail) {
      return res
        .status(404)
        .json({ success: false, message: 'AI email not found.' });
    }

    const reviewedBy = req.user && req.user.id ? req.user.id : null;
    const updated = await manualSendAiEmail(aiEmail, {
      draft: req.body && req.body.draft,
      reviewedBy,
    });

    res.json({ success: true, email: updated });
  } catch (error) {
    console.error('Manual send error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
});

// ── Reject ──
router.post('/:id/reject', authenticate, isAdmin, async (req, res) => {
  try {
    const aiEmail = await AiEmail.findById(req.params.id);
    if (!aiEmail) {
      return res
        .status(404)
        .json({ success: false, message: 'AI email not found.' });
    }
    aiEmail.status = 'rejected';
    aiEmail.requiresHumanReview = false;
    aiEmail.reviewReason =
      (req.body && req.body.reason) || 'Rejected by administrator.';
    if (req.user && req.user.id) {
      aiEmail.reviewedBy = req.user.id;
      aiEmail.reviewedAt = new Date();
    }
    await aiEmail.save();
    res.json({ success: true, email: aiEmail });
  } catch (error) {
    console.error('Reject error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
});

// ── Test endpoints ──
router.post('/test', authenticate, isAdmin, async (req, res) => {
  try {
    const { messageId, from, to, subject, body, threadId, receivedAt } =
      req.body;

    if (!from) {
      return res
        .status(400)
        .json({ success: false, message: 'from is required.' });
    }
    if (!body) {
      return res
        .status(400)
        .json({ success: false, message: 'body is required.' });
    }

    const email = await processIncomingEmail({
      messageId:
        messageId ||
        `test-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`,
      threadId: threadId || null,
      from,
      to: to || 'info@bothellselect.com',
      subject: subject || '',
      body,
      receivedAt: receivedAt || new Date(),
    });

    res.status(201).json({ success: true, email });
  } catch (error) {
    console.error('Error processing AI email:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to process email through AI assistant.',
      error: error.message,
    });
  }
});

router.post('/ingest-test', authenticate, isAdmin, async (req, res) => {
  try {
    const { messageId, threadId, from, to, subject, body, receivedAt } =
      req.body;

    if (!from) {
      return res
        .status(400)
        .json({ success: false, message: 'from is required.' });
    }
    if (!body) {
      return res
        .status(400)
        .json({ success: false, message: 'body is required.' });
    }

    const email = await processIncomingEmail({
      messageId:
        messageId ||
        `ingest-test-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`,
      threadId: threadId || null,
      from,
      to: to || 'bothellselect@proton.me',
      subject: subject || '',
      body,
      receivedAt: receivedAt || new Date(),
    });

    res.status(201).json({ success: true, email });
  } catch (error) {
    console.error('Error ingesting test email:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to ingest test email.',
      error: error.message,
    });
  }
});

module.exports = router;
